Removed dependency on ptools (breaks Origen for Windows)
Origen-SDK/origen_memory_image pull request #1
Opened 2017-09-27 16:55 UTC by pderouen

The ptools GEM causes File.basepath to behave differently in Windows which causes a run time error when Origen creates output files.  Since ptools was only being used to detect whether or not a file is a binary file, it makes sense to simply remove this dependency.  This PR does just that.

2017-09-28 07:43 UTC, ginty requested changes
I like the change and would be happy to lose this dependency.
However, the code additions here are close copies of the original which has no explicit license terms associated with it.
Could you solve the same problem with original code to avoid any future issues associated with this showing up in code scans?

2017-09-28 14:41 UTC, pderouen commented
@ginty how's this?

2017-09-29 06:52 UTC, ginty approved these changes
LGTM, added you as a gem owner so release at will

2017-09-29 15:01 UTC, rlaj reviewed
Looks good to me.  (And it didn't break my app:)

2017-09-29 15:01 UTC, rlaj approved these changes

2017-09-29 15:03 UTC, merged